### ISSUE TITLE
Numbers aren't displaying in the HUD

### ISSUE THREAD

**Issue by Cruuk** [Tslat/TslatEntityStatus#14]
![image](https://github.com/Tslat/TslatEntityStatus/assets/38159897/68c9dacb-bb87-4474-bf58-9453e8f49ea8)

Even with the mod by itself on the latest versions, I have been unable to find why this happens. This has been tested with a default config. I've also tried changing the health display to NUMERIC, but it doesn't change anything besides the bar being gone.

So far, it seems to only be happening to me, because in a certain someone's stream, the number displayed for them. According to them they're also on the default config. While not completely exhaustive yet, I've tried a couple other things like changing GUI size, particles, etc. None have worked.

I unfortunately haven't found why this happens yet, so I am currently lost

**Comment by Tslat** [comment]
Yeah it also works fine for me both in dev, and with AoA in-dev
