### ISSUE TITLE
Version 1.20.1 bug

### ISSUE THREAD

**Issue by 1534505706** [Tslat/TslatEntityStatus#15]
Version 1.20.1 crashes as soon as it targets what ItemsAdder does (non-blocks) in the server，I hope the author will fix it quickly

**Comment by Tslat** [comment]
Provide the crash report

**Comment by 1534505706** [comment]
[Error reporting-2023-6-30_10.34.23.zip](https://github.com/Tslat/TslatEntityStatus/files/11912278/Error.reporting-2023-6-30_10.34.23.zip)
[crash-2023-06-30_10.35.27-client.txt](https://github.com/Tslat/TslatEntityStatus/files/11912279/crash-2023-06-30_10.35.27-client.txt)
thanks

**Comment by Tslat** [comment]
It's crashing because a tag that fabric adds itself is missing

I'm not sure there's anything I can do on my side for this - if they're messing with fabric tags that's on them

**Comment by 1534505706** [comment]
Thank you author
