### ISSUE TITLE
Blood volume digital display

### ISSUE THREAD

**Issue by wsxiya** [Tslat/TslatEntityStatus#21]
The digital display of the creature's health volume has been increased to be displayed next to the armor value.
It would be great if it could be like the picture below, but I can't upload the picture, I can only upload a compressed file
[1.zip](https://github.com/Tslat/TslatEntityStatus/files/12817606/1.zip)

**Comment by Tslat** [comment]
Why would you want to display the mob's health twice? it already has a health bar

**Comment by wsxiya** [comment]
> 为什么要显示两次生物的生命值？它已经有一个健康栏

I think what I mean is that the health value displayed on the health bar is displayed next to the armor value like the creature's armor value. Nothing is displayed on the health bar, but next to the armor value, Add a creature health value display, for example: "♥x(**)". (I am using Google Translate)

**Comment by Tslat** [comment]
Have you seen the hearts option for the bar style in the config?

**Comment by wsxiya** [comment]
> 您是否在配置中看到条形样式的心形选项？

Sorry, I didn't see this option because my English was translated using translation software. If there is this option, can you tell me which option it is?

**Comment by wsxiya** [comment]
When I set the "HUD Health render type" option to Bar, the creature's health value will not be displayed, only the creature's health bar will be displayed.
When I set the "HUD Health render type" option to Numeric, the creature's health bar will not be displayed, but only the creature's health value will be displayed.
