### ISSUE TITLE
[BUG]1.16.5

### ISSUE THREAD

**Issue by 2929762171** [Tslat/TslatEntityStatus#22]
【1】inWorldHudArmour = true
![WI49V%){S~{M}NC E)K(7FP](https://github.com/Tslat/TslatEntityStatus/assets/98941945/721f8214-9069-44a2-956f-738fda37795c)
Cause this:
![image](https://github.com/Tslat/TslatEntityStatus/assets/98941945/1073712a-3217-43cc-a35f-99862bd6bd23)

【2】With mod "ReachFix-1.16.5-1.0.1.jar" will lost this HUD:
![image](https://github.com/Tslat/TslatEntityStatus/assets/98941945/2ee7a58f-3daf-44fe-bd97-c1d596a61862)

**Comment by Tslat** [comment]
1.16.5 is out of scope unfortunately, just too old
