### ISSUE TITLE
AutoLeveling Compatibility

### ISSUE THREAD

**Issue by norfaremc** [Tslat/TslatEntityStatus#29]
Would love some compatibility with the Auto Leveling mod so the level doesnt look weird or glitch into the health bar! Thank you so much for your hard work, your mod is amazing!!

**Comment by Tslat** [comment]
Got examples of the issue?
I have no idea what you're referring to

**Comment by norfaremc** [comment]
Not an issue, but an enhancement or request! And yeah, I'm so sorry, I really should've elaborated better!

I'm looking to make the switch in our modpack from using the Neat bars to your health bars, because yours looks WAY better... But Neat has compatibility with this mod called Auto Leveling: https://www.curseforge.com/minecraft/mc-mods/auto-leveling
Auto Leveling will display the level above a player or a mob's head, but it clips into the health bar sometimes with your mod. Neat's compatibility puts the level on the bar itself, and I was wondering if you'd ever be willing to work on a compatibility for it like that? I think it would look so great, and really solidify what I'm lookin for in a health bar! :) 

Here's an example of the health bar with the level next to it. Most of the time, the lvl is really far away from the bar, but sometimes itll clip into the bar if the name of the creature is less than 5 characters long.
![2024-01-11_12 46 01](https://github.com/Tslat/TslatEntityStatus/assets/133526827/6b7c0275-6d03-490c-b879-8a2adf35ffab)

**Comment by Tslat** [comment]
🤔 
Alright

**Comment by Tslat** [comment]
@norfaremc 
So i looked into this
The most I could realistically do is move my bar up and out of the way of the level thing if it's present, but the level would still be in the wrong place and be virtually broken

This needs to be done as a compat on AutoLeveling's side
