### ISSUE TITLE
Configuration file question, the hudRenderPosition key.

### ISSUE THREAD

**Issue by RepentStar** [Tslat/TslatEntityStatus#33]
Since there is no way to implement in-game configuration with this mod, I went to manually modify the config file. I wanted to move the position of the hud's in-game display and found the relevant configuration key `hudRenderPosition`. However, I checked the [Wiki](https://github.com/Tslat/TslatEntityStatus/wiki/User-Configuration) and did not find the key `hudRenderPosition`. Is it possible to update the Wiki if hud can be displayed above the target entity and follow it?   

Thanks for writing this mod! :)

**Comment by Tslat** [comment]
Oops yeah I forgot to update the config page

That being said - if you're on forge you can use [configured](https://www.curseforge.com/minecraft/mc-mods/configured)
If you're on fabric, midnightlib should be available

**Comment by RepentStar** [comment]
Thanks for your help. Have a nice day. :)
