### ISSUE TITLE
add Compatibility with ModernUI mod

### ISSUE THREAD

**Issue by Yumileashen** [Tslat/TslatEntityStatus#34]
great mod btw
the text was error, just rendering boxes like ▯▯▯▯▯
for ModernUI mod link
https://github.com/BloCamLimb/ModernUI-MC

**Comment by Tslat** [comment]
I don't think there's anything on my side I can do for this
This might be a bug on ModernUI's side

**Comment by remidu64** [comment]
[made an issue at ModernUI's github repo](https://github.com/BloCamLimb/ModernUI/issues/265)
