### ISSUE TITLE
In-world HUD mob name moving with camera

### ISSUE THREAD

**Issue by alexmako50** [Tslat/TslatEntityStatus#35]
![2024-02-29_10 55 57](https://github.com/Tslat/TslatEntityStatus/assets/82992013/ee9f4acd-184d-4cf4-9bf8-9e9fb539168a)
When moving in the game, the white text moves with the camera, creating another copy of the mob name.
For reference, i only have 3 mods (this, fabric-api and midnightlib), no texture packs, and no shaders (playing in 1.20.1 but i tested in 1.20.4 and the same thing happened)

**Comment by alexmako50** [comment]
If i add FOV to the game, the white text broke in the same way

**Comment by rezomusic** [comment]
![2024-03-12_20 20 13](https://github.com/Tslat/TslatEntityStatus/assets/97917447/2c3e6b5a-e386-4933-b6a9-8b42d457771d)
I know this has already been marked as a bug, but just wanted to confirm this is happening with health text as well. I am having the same problem. Text is rendering outside of the box on the combined bar setting.
