### ISSUE TITLE
[BUG] Even with server-requiring features disabled, cannot join vanilla servers

### ISSUE THREAD

**Issue by daniel-koval** [Tslat/TslatEntityStatus#38]
With this mod, even with all config options disabled, the following error occurs when trying to join a non-Neoforge server. "You are trying to connect to a server that is not running Neoforge, but you have mods that require it. A connection could not be established."

**Comment by Tslat** [comment]
What version of TES is this on

**Comment by daniel-koval** [comment]
1.5.5

**Comment by Tslat** [comment]
Fixed in 1.6
