### ISSUE TITLE
Additional characteristics of horses, donkeys, mules, llamas and camels.

### ISSUE THREAD

**Issue by CtrelokCvobods** [Tslat/TslatEntityStatus#39]
Hi.
I was looking for a mod that allows you to display the characteristics of horses, but I did not find the perfect one.
1. [Horse Statistics](https://modrinth.com/mod/horse-statistics) - it only works on Forge.
2. [Horse Stats Vanilla](https://modrinth.com/mod/horsestatsvanilla) - it only works on Fabric and Quilt, opens the characteristics only in the inventory, therefore requires taming.

Adding these characteristics to horses seems logical:
- Maximum health (color: 🟥weak, 🟨 medium, 🟩 maximum);
- Speed (color: 🟥weak, 🟨 medium, 🟩 maximum);
- Jump (color: 🟥weak, 🟨 medium, 🟩 maximum);
- Availability of chests (inventory slots).

**Comment by Tslat** [comment]
Added in 1.21-1.6

![image](https://github.com/Tslat/TslatEntityStatus/assets/7098525/5dd424ca-38e0-4bc8-af41-3075a7fc2141)
