### ISSUE TITLE
Wrong Config option names in lang

### ISSUE THREAD

**Issue by VusyBery** [Tslat/TslatEntityStatus#43]
The following config options use a different name in-game from the one found in the lang file :

hudArmourFontStyle
inWorldHudForSelf
defaultParticleLifespan
teamBasedDamageParticleColours

The name displayed for these four options in-game is an exact transcription with proper capitalization and spacing of the config names, leading me to believe that their lang links are broken somehow. This also means that they do not translate properly when switching langs.
Also because of this, the first two are the only config names in-game where "Hud" is not fully capitalized as "HUD"

**Comment by Tslat** [comment]
Can't replicate

Is this a specific version and/or platform or something?

**Comment by VusyBery** [comment]
Latest version at the time I posted this issue, in any case

**Comment by Tslat** [comment]
I'm gonna close this then

if it comes back up with more info then I can look into it
