### ISSUE TITLE
HUD Entity Icon Bug/Broken Behaviour

### ISSUE THREAD

**Issue by radioactive-exe** [Tslat/TslatEntityStatus#44]
The entity model in the HUD is bugged and broken when using model-altering things such as the Fresh Animations resource pack, which is what I am using here (using EMF/ETF). More peculiarly, this behaviour is somehow connected to unhiding and hiding the HUD (f1). Here's a video demonstrating the weird situation.

PS: Apologies for the sped-up and low-quality video - still had to get enough demonstration and stay within GitHub's media size limit!

https://github.com/user-attachments/assets/c5713eeb-3689-499a-aafb-c19ba3d32803

**Comment by Tslat** [comment]
I would recommend reporting this to them too

I'm not sure there's even anything I can do from my side

**Comment by radioactive-exe** [comment]
Hello! Apologies for the very old thread being bumped up, I have been afk for the last half a year but have now returned to usual. I have reported this to Fresh Animations and upon discussing it seems like there is nothing they can do from their end either. Is there any way to specify what stage of the render passes are shown on the HUD? I.e. before applying textures, after applying animations, etc. I have been deep-diving into the source code of TES but I am quite new to the modding sphere so I am unsure as to how the default entity rendered comes packaged (with/without custom textures, etc.) and how this can be manipulated.

**Comment by radioactive-exe** [comment]
Hello! Apologies for the very old thread being bumped up, I have been afk for the last half a year but have now returned to usual. I have reported this to Fresh Animations and upon discussing it seems like there is nothing they can do from their end either. Is there any way to specify what stage of the render passes are shown on the HUD? I.e. before applying textures, after applying animations, etc. I have been deep-diving into the source code of TES but I am quite new to the modding sphere so I am unsure as to how the default entity rendered comes packaged (with/without custom textures, etc.) and how this can be manipulated. Also, @Tslat I unfortunately still have this issue in 1.21.4 with the updated versions of EMF/ETF, TES, and FA. Hopefully this issue can be reopened and possible information might be recouped to see what can be done? If there is any further information or details or steps that I can take, I would be happy to oblige.

**Comment by Tslat** [comment]
I mean functionally all I'm doing is grabbing the entity, resetting it to a pseudo-default state, rendering it with its normal renderer, then undoing the reset

I'm not sure how fresh animations works but I suspect they're doing some sort of model transformation during rendering that doesn't know how to account for the render in HUD

Either way, the entry to rendering the entity is here
https://github.com/Tslat/TslatEntityStatus/blob/7236d0084d8f6e5dddcf8a55c3e702508fc2cf9c/Common/src/main/java/net/tslat/tes/core/hud/TESHud.java#L138

With the actual rendering happening here:
https://github.com/Tslat/TslatEntityStatus/blob/7236d0084d8f6e5dddcf8a55c3e702508fc2cf9c/Common/src/main/java/net/tslat/tes/api/util/TESClientUtil.java#L145

**Comment by radioactive-exe** [comment]
Does the pseudo-reset include clearing the pose-stack or similar things that essentially A-Pose the mob again or reset the UV unwrapping? I’ve noticed texture issues for a few mobs with extra model parts as well, such as Better Vanilla Building’s biome skeletons, which appear broken texturally on the HUD and led me to believe the UV is a step that’s being reset and then being reinitialised incompletely. What if you were to render the entity immediately without resetting? (Besides the view rotation/location etc.) would that render incorrectly? Or would there be stages in the reset that would be possibly attached to this?

**Comment by Tslat** [comment]
It does not reset the UV, no

PoseStack manipulation is an inevitability, and if a renderer relies on the posestack being in a certain state to render properly then there's literally nothing anyone can do, that's just poor design
