### ISSUE TITLE
Inconsistent behaviour with boss mobs

### ISSUE THREAD

**Issue by thebertster** [Tslat/TslatEntityStatus#49]
Version 1.6.2/1.6.3 Fabric with Minecraft 1.21.1 - tested with no other mods loaded other than ModMenu.

TES HUD still displays for Wither when `hudBossesEnabled = False`

![2024-09-15_10 53 14](https://github.com/user-attachments/assets/17ef7e28-b471-4789-bd6a-baf3bb76c209)

TES HUD does not display for Ender Dragon when `hudBossesEnabled = True`

**Comment by Tslat** [comment]
Fixed in 1.21.1
