### ISSUE TITLE
Feature request: Entity blacklist

### ISSUE THREAD

**Issue by Jay420blaze** [Tslat/TslatEntityStatus#52]
Sorry for another feature request but would also love to see an entity blacklist in the 1.20.1 version. I saw an error from earlier this year was closed saying this was added in 1.5 however im unable to find it in the config of version 1.5.1 for minecraft 1.20.1. Would love to see this, and if it's already in the config and I somehow missed it please let me know.

**Comment by Tslat** [comment]
Tag any entities you don't want handled with the `tslatentitystatus:no_tes_handling` entitytype tag

**Comment by Jay420blaze** [comment]
Ah i see, i forget datapacks are even a thing lol.

For anyone looking this up in the future thats unsure on how to do this, you need to create a datapack with the defined entity tag that Tslat mentioned above then give a list of mobs in the "Values" section. a website i found to do this easily is:

https://far.ddns.me/dev

Just ensure to change the entity_tag_type to the above tag then get to listing entitles you don't want showing up.

Thanks Tslat!
