### ISSUE TITLE
[Bug] Health points don't show with Xaero's Minimap version 24.6.1

### ISSUE THREAD

**Issue by SmokyTheCat** [Tslat/TslatEntityStatus#53]
For Fabric, when Xaero's Minimap version 24.6.1 & 24.6.2 is installed the counter of the health points don't appear, this affects Minecraft 1.21.1 and 1.21.3

With Xaero's Minimap 24.6.1 & 24.6.2:
![2024-11-10_13 06 09](https://github.com/user-attachments/assets/8556e88d-510a-499d-9bcb-800150de8809)
The numbers disappear with the transparent background still there

With Xaero's Minimap 24.6.0:
![2024-11-10_13 13 44](https://github.com/user-attachments/assets/def50753-cd5c-4639-af4f-251af24cc777)
The numbers were not affected with this version and older versions of Minimap

This doesn't happen with Xaero's World Map only with their Minimap.

**Comment by Tslat** [comment]
Has this been reported to Xaero?
