### ISSUE TITLE
Porting to 1.21.4

### ISSUE THREAD

**Issue by YOMA8338** [Tslat/TslatEntityStatus#62]
If you use the mod for 1.21.3 as is, you will have a problem with damage particles not showing up, but otherwise you can use it as is.
So porting seems easy, but I am not familiar with Java, so I don't know how hard it is.
I would like to see the mod ported for 1.21.4 if possible.

**Comment by YOMA8338** [comment]
By the way, I have only confirmed that mods for 1.21.3 can be used as they are in 1.21.4 only in Fabric.

**Comment by Tslat** [comment]
It will be ported for 1.21.4

Unfortunately it got held up by ForgeConfigAPIPort not pushing out versions

But I'm working on it
